name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discord
        run: |

           AUTHOR="${{ github.actor }}"
           BRANCH="${{ github.ref_name }}"
           MESSAGE="${{ github.event.head_commit.message }}"
            REPO="${{ github.repository }}"
            COMMIT_URL="${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"

            curl -v \
              -H "Content-Type: application/json" \
              -X POST \
              -d "{\"content\":\"🚀 New push to $BRANCH\n👤 Author: $AUTHOR\n📦 Repository: $REPO\n📝 Commit: $MESSAGE\n🔗 $COMMIT_URL\n✅ Status: Success\"}" \
              "${{ secrets.DISCORD_WEBHOOK }}"


            